// types/index.ts
export interface UserDoc {
  id: string; // Auth0 sub
  Name: string;
  Email: string;
  Groups: string[]; // Array of group IDs
  Phone: string;
  Address: string;
}

export interface GroupDoc {
  id: string; // Optional since it's generated by the function
  Name: string;
  OwnerId: string; // Auth0 sub
  MemberIds: string[]; // Array of Auth0 subs
  Description: string;
  SkillLevel: string;
  Privacy: string;
  HomeCourt: string;
  MeetingSchedule: string;
}

export interface EventDoc {
  id: string;
  GroupIDs?: string[]; // Array of group IDs - now optional
  IndividualParticipantIDs?: string[]; // Array of individual user IDs - new field
  Title: string;
  EventDate: Date;
  Location: string;
  CutoffDate?: Date; // Voting cutoff date - now optional
  CreatorID: string; // Auth0 sub
  VotingEnabled?: boolean; // New field to indicate if voting is enabled
}

export interface VoteDoc {
  userId: string; // Auth0 sub (also used as document ID)
  Status: VoteStatus;
  VotedAt: Date;
}

export interface VoteCountsDoc {
  going: number;
  maybe: number;
  not: number;
  total: number;
  lastUpdated: Date;
}

export interface VoteShard {
  going: number;
  maybe: number;
  not: number;
}

export type VoteStatus = 'going' | 'maybe' | 'not';

export interface CreateGroupData {
  name: string;
  description?: string;
}

export interface CreateEventData {
  groupId: string;
  title: string;
  description?: string;
  date: Date;
  location: string;
  cutoff: Date;
}

export interface UpdateEventData {
  title?: string;
  description?: string;
  date?: Date;
  location?: string;
  cutoff?: Date;
}

export interface newMatchHistory {
  team1: [
    player1Id: string,
    player2Id: string,
    score: number
  ];
  team2: [
    player1Id: string,
    player2Id: string,
    score: number
  ]
  date: Date
}

export interface FirebaseError {
  code: string;
  message: string;
}
